### ISSUE TITLE
--port 9229 is causing a crash

### ISSUE THREAD

**Issue by rluncasu** [tiaanduplessis/kill-port#11]
root@7a607b52938a:/app# kill-port --port 9229
/usr/local/lib/node_modules/kill-port/cli.js:9
let port = args.port ? args.port.split(',') : args.unknown
                                 ^

TypeError: args.port.split is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/kill-port/cli.js:9:34)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by tiaanduplessis** [comment]
@rluncasu it should be fixed in 1.3.1. Thanks for reporting 👍

**Comment by rluncasu** [comment]
Ah , you beat me to it, was actually submitting a PR when the notification came in :), thanks !
